### PR TITLE
#160069604 create sign up and sign in pages 

### PR DESCRIPTION
**Pull request by ThaDeveloper**
#### What does this PR do?
Have user sign up and sign in pages
#### Description of Task to be completed?
Present user with sign up and sign in forms
#### How should this be manually tested?
Open the html template files in your favorite browser
#### Any background context you want to provide?
Built in:
- HTML5
- CSS3
#### What are the relevant pivotal tracker stories?
#160069604
#### Screenshots 
Sign Up
signup

Sign In
sign

### CODE REVIEW

**Comment by danielotieno** [comment]
Neat! I love this

**Comment by gwako94** [comment]
Awesome UI

**Comment by EmmanuelBeja** [comment]
Looks apealling. UX is good

**Comment by menyagah** [comment]
I love the colors and simplicity of the website.

**Pull request merged**
